Hw03 mongodb
Dmytro80/nodejs-homework-rest-api pull request #2
Opened 2023-01-14 17:14 UTC by Dmytro80

Прошу перевірити ДЗ №3

2023-01-14 18:45 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-14 18:45 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-14 18:45 UTC, KhYulian commented on models/contact.js
> +});
Винесіть схеми Joi в окремий файл contactSchema, updateStatusSchema

2023-01-14 18:45 UTC, KhYulian commented on helpers/index.js
> +}
можна створити одини загальний клас, який прийматиме message, statusCode

2023-01-14 18:45 UTC, KhYulian commented on helpers/index.js
> +}
Або додайте дефолтні повідомлення до ваших класів

2023-01-14 20:14 UTC, Dmytro80 commented on server.js
> +main();
Зроблено

2023-01-14 20:18 UTC, Dmytro80 commented on models/contact.js
> +});
Створено окрему папку Schemas та винесено туди в окремому файлі схеми Joi  (contactSchema та updateStatusSchema)

2023-01-14 20:19 UTC, Dmytro80 commented on helpers/index.js
> +}
Створено загальний клас, що приймає message та status

2023-01-15 07:12 UTC, KhYulian approved these changes
Чудова робота!

2023-01-15 07:12 UTC, merged